%% load full mass model (max 28000kg)
load('C:\Users\Markus\Documents\Uni\WISE2021\Projektseminar\PS_Luftbetankung\PS_Luftbetankung_newRepo\Projekteseminar-Luftbetankung\Code\Messungen\step_v_massmodel_1.mat')
step_v_m2 = out;
clear out;
load('C:\Users\Markus\Documents\Uni\WISE2021\Projektseminar\PS_Luftbetankung\PS_Luftbetankung_newRepo\Projekteseminar-Luftbetankung\Code\Messungen\step_phi_massmodel_1.mat')
step_phi_m2 = out;
clear out;
load('C:\Users\Markus\Documents\Uni\WISE2021\Projektseminar\PS_Luftbetankung\PS_Luftbetankung_newRepo\Projekteseminar-Luftbetankung\Code\Messungen\step_theta_massmodel_1.mat')
step_theta_m2 = out;
clear out;
load('C:\Users\Markus\Documents\Uni\WISE2021\Projektseminar\PS_Luftbetankung\PS_Luftbetankung_newRepo\Projekteseminar-Luftbetankung\Code\Messungen\step_h_massmodel_1.mat')
step_h_m2 = out;
clear out;

load('C:\Users\Markus\Documents\Uni\WISE2021\Projektseminar\PS_Luftbetankung\PS_Luftbetankung_newRepo\Projekteseminar-Luftbetankung\Code\Messungen\step_v_massmodel_2.mat')
step_v_m3 = out;
clear out;
load('C:\Users\Markus\Documents\Uni\WISE2021\Projektseminar\PS_Luftbetankung\PS_Luftbetankung_newRepo\Projekteseminar-Luftbetankung\Code\Messungen\step_phi_massmodel_2.mat')
step_phi_m3 = out;
clear out;
load('C:\Users\Markus\Documents\Uni\WISE2021\Projektseminar\PS_Luftbetankung\PS_Luftbetankung_newRepo\Projekteseminar-Luftbetankung\Code\Messungen\step_theta_massmodel_2.mat')
step_theta_m3 = out;
clear out;
load('C:\Users\Markus\Documents\Uni\WISE2021\Projektseminar\PS_Luftbetankung\PS_Luftbetankung_newRepo\Projekteseminar-Luftbetankung\Code\Messungen\step_h_massmodel_2.mat')
step_h_m3 = out;
clear out;


%% alle y für zwei massen modelle
f_all_out = figure;
subplot(8,4,1)
plot(step_v_m2.step_linear.Time, step_v_m2.step_linear.Data(:,1), ':k', ...
    step_v_m2.outputs_linear.Time, step_v_m2.outputs_linear.Data(:,1), '--r', ...
    step_v_m3.outputs_linear.Time, step_v_m3.outputs_linear.Data(:,1), '--b', ...
    step_v_m2.outputs_nonlinear.Time, step_v_m2.outputs_nonlinear.Data(:,1), '-.r', ...
    step_v_m3.outputs_nonlinear.Time, step_v_m3.outputs_nonlinear.Data(:,1), '-.b');
legend('step', 'linear, Model 2', 'linear, Model 3', 'nonlinear, Model 2', 'nonlinear, Model 3', 'Location', 'southeast')
ylim([0 1.2]);
ylabel('to v1 [m/s]');
title('\rm from w_{v1}')
grid on;
subplot(8,4,5)
plot(step_v_m2.outputs_linear.Time, step_v_m2.outputs_linear.Data(:,2), '--r', ...
    step_v_m3.outputs_linear.Time, step_v_m3.outputs_linear.Data(:,2), '--b', ...
    step_v_m2.outputs_nonlinear.Time, step_v_m2.outputs_nonlinear.Data(:,2), '-.r', ...
    step_v_m3.outputs_nonlinear.Time, step_v_m3.outputs_nonlinear.Data(:,2), '-.b');
ylim(1e-2*[-0.2 0.2]);
ylabel('to \Phi1 [rad]');
grid on;
subplot(8,4,9)
plot(step_v_m2.outputs_linear.Time, step_v_m2.outputs_linear.Data(:,3), '--r', ...
    step_v_m3.outputs_linear.Time, step_v_m3.outputs_linear.Data(:,3), '--b', ...
    step_v_m2.outputs_nonlinear.Time, step_v_m2.outputs_nonlinear.Data(:,3), '-.r', ...
    step_v_m3.outputs_nonlinear.Time, step_v_m3.outputs_nonlinear.Data(:,3), '-.b');
ylim([-0.1 0]);
ylabel('to \Theta1 [rad]');
grid on;
subplot(8,4,13)
plot(step_v_m2.outputs_linear.Time, step_v_m2.outputs_linear.Data(:,4), '--r', ...
    step_v_m3.outputs_linear.Time, step_v_m3.outputs_linear.Data(:,4), '--b', ...
    step_v_m2.outputs_nonlinear.Time, step_v_m2.outputs_nonlinear.Data(:,4), '-.r', ...
    step_v_m3.outputs_nonlinear.Time, step_v_m3.outputs_nonlinear.Data(:,4), '-.b');
ylim([4997 5002]);
ylabel('to h1 [m]');
grid on;
subplot(8,4,17)
plot(step_v_m2.outputs_linear.Time, step_v_m2.outputs_linear.Data(:,5), '--r', ...
    step_v_m3.outputs_linear.Time, step_v_m3.outputs_linear.Data(:,5), '--b', ...
    step_v_m2.outputs_nonlinear.Time, step_v_m2.outputs_nonlinear.Data(:,5), '-.r', ...
    step_v_m3.outputs_nonlinear.Time, step_v_m3.outputs_nonlinear.Data(:,5), '-.b');
ylim(1e-2*[-1 1]);
ylabel('to \Delta v [m/s]');
grid on;
subplot(8,4,21)
plot(step_v_m2.outputs_linear.Time, step_v_m2.outputs_linear.Data(:,6), '--r', ...
    step_v_m3.outputs_linear.Time, step_v_m3.outputs_linear.Data(:,6), '--b', ...
    step_v_m2.outputs_nonlinear.Time, step_v_m2.outputs_nonlinear.Data(:,6), '-.r', ...
    step_v_m3.outputs_nonlinear.Time, step_v_m3.outputs_nonlinear.Data(:,6), '-.b');
ylim(1e-2*[-0.5 0.5]);
ylabel('to \Delta \Phi [rad]');
grid on;
subplot(8,4,25)
plot(step_v_m2.outputs_linear.Time, step_v_m2.outputs_linear.Data(:,7), '--r', ...
    step_v_m3.outputs_linear.Time, step_v_m3.outputs_linear.Data(:,7), '--b', ...
    step_v_m2.outputs_nonlinear.Time, step_v_m2.outputs_nonlinear.Data(:,7), '-.r', ...
    step_v_m3.outputs_nonlinear.Time, step_v_m3.outputs_nonlinear.Data(:,7), '-.b');
ylim(1e-1*[-0.5 0.5]);
ylabel('to \Delta \Theta [rad]');
grid on;
subplot(8,4,29)
plot(step_v_m2.outputs_linear.Time, step_v_m2.outputs_linear.Data(:,8), '--r', ...
    step_v_m3.outputs_linear.Time, step_v_m3.outputs_linear.Data(:,8), '--b', ...
    step_v_m2.outputs_nonlinear.Time, step_v_m2.outputs_nonlinear.Data(:,8), '-.r', ...
    step_v_m3.outputs_nonlinear.Time, step_v_m3.outputs_nonlinear.Data(:,8), '-.b');
ylim([-15 -5]);
ylabel('to \Delta h [m]');
xlabel('Time [s]');
grid on;

subplot(8,4,2)
plot(step_phi_m2.outputs_linear.Time, step_phi_m2.outputs_linear.Data(:,1), '--r', ...
    step_phi_m3.outputs_linear.Time, step_phi_m3.outputs_linear.Data(:,1), '--b', ...
    step_phi_m2.outputs_nonlinear.Time, step_phi_m2.outputs_nonlinear.Data(:,1), '-.r', ...
    step_phi_m3.outputs_nonlinear.Time, step_phi_m3.outputs_nonlinear.Data(:,1), '-.b');
ylim([-0.05 0.15]);
title('\rm from w_{\Phi1}')
grid on;
subplot(8,4,6)
plot(step_phi_m2.step_linear.Time, step_phi_m2.step_linear.Data(:,2), ':k', ...
    step_phi_m2.outputs_linear.Time, step_phi_m2.outputs_linear.Data(:,2), '--r', ...
    step_phi_m3.outputs_linear.Time, step_phi_m3.outputs_linear.Data(:,2), '--b', ...
    step_phi_m2.outputs_nonlinear.Time, step_phi_m2.outputs_nonlinear.Data(:,2), '-.r', ...
    step_phi_m3.outputs_nonlinear.Time, step_phi_m3.outputs_nonlinear.Data(:,2), '-.b');
ylim([-0.05 0.3]);
grid on;
subplot(8,4,10)
plot(step_phi_m2.outputs_linear.Time, step_phi_m2.outputs_linear.Data(:,3), '--r', ...
    step_phi_m3.outputs_linear.Time, step_phi_m3.outputs_linear.Data(:,3), '--b', ...
    step_phi_m2.outputs_nonlinear.Time, step_phi_m2.outputs_nonlinear.Data(:,3), '-.r', ...
    step_phi_m3.outputs_nonlinear.Time, step_phi_m3.outputs_nonlinear.Data(:,3), '-.b');
ylim([-0.1 0]);
grid on;
subplot(8,4,14)
plot(step_phi_m2.outputs_linear.Time, step_phi_m2.outputs_linear.Data(:,4), '--r', ...
    step_phi_m3.outputs_linear.Time, step_phi_m3.outputs_linear.Data(:,4), '--b', ...
    step_phi_m2.outputs_nonlinear.Time, step_phi_m2.outputs_nonlinear.Data(:,4), '-.r', ...
    step_phi_m3.outputs_nonlinear.Time, step_phi_m3.outputs_nonlinear.Data(:,4), '-.b');
ylim([4990 5005]);
grid on;
subplot(8,4,18)
plot(step_phi_m2.outputs_linear.Time, step_phi_m2.outputs_linear.Data(:,5), '--r', ...
    step_phi_m3.outputs_linear.Time, step_phi_m3.outputs_linear.Data(:,5), '--b', ...
    step_phi_m2.outputs_nonlinear.Time, step_phi_m2.outputs_nonlinear.Data(:,5), '-.r', ...
    step_phi_m3.outputs_nonlinear.Time, step_phi_m3.outputs_nonlinear.Data(:,5), '-.b');
ylim([-0.2 0.2]);
grid on;
subplot(8,4,22)
plot(step_phi_m2.outputs_linear.Time, step_phi_m2.outputs_linear.Data(:,6), '--r', ...
    step_phi_m3.outputs_linear.Time, step_phi_m3.outputs_linear.Data(:,6), '--b', ...
    step_phi_m2.outputs_nonlinear.Time, step_phi_m2.outputs_nonlinear.Data(:,6), '-.r', ...
    step_phi_m3.outputs_nonlinear.Time, step_phi_m3.outputs_nonlinear.Data(:,6), '-.b');
ylim(1e-1*[-0.5 0.5]);
grid on;
subplot(8,4,26)
plot(step_phi_m2.outputs_linear.Time, step_phi_m2.outputs_linear.Data(:,7), '--r', ...
    step_phi_m3.outputs_linear.Time, step_phi_m3.outputs_linear.Data(:,7), '--b', ...
    step_phi_m2.outputs_nonlinear.Time, step_phi_m2.outputs_nonlinear.Data(:,7), '-.r', ...
    step_phi_m3.outputs_nonlinear.Time, step_phi_m3.outputs_nonlinear.Data(:,7), '-.b');
ylim(1e-1*[-0.5 0.5]);
grid on;
subplot(8,4,30)
plot(step_phi_m2.outputs_linear.Time, step_phi_m2.outputs_linear.Data(:,8), '--r', ...
    step_phi_m3.outputs_linear.Time, step_phi_m3.outputs_linear.Data(:,8), '--b', ...
    step_phi_m2.outputs_nonlinear.Time, step_phi_m2.outputs_nonlinear.Data(:,8), '-.r', ...
    step_phi_m3.outputs_nonlinear.Time, step_phi_m3.outputs_nonlinear.Data(:,8), '-.b');
ylim([-15 -5]);
xlabel('Time [s]');
grid on;

subplot(8,4,3)
plot(step_theta_m2.outputs_linear.Time, step_theta_m2.outputs_linear.Data(:,1), '--r', ...
    step_theta_m3.outputs_linear.Time, step_theta_m3.outputs_linear.Data(:,1), '--b', ...
    step_theta_m2.outputs_nonlinear.Time, step_theta_m2.outputs_nonlinear.Data(:,1), '-.r', ...
    step_theta_m3.outputs_nonlinear.Time, step_theta_m3.outputs_nonlinear.Data(:,1), '-.b');
ylim([-60 30]);
xlim([0 50]);
title('\rm from w_{\Theta1}')
grid on;
subplot(8,4,7)
plot(step_theta_m2.outputs_linear.Time, step_theta_m2.outputs_linear.Data(:,2), '--r', ...
    step_theta_m3.outputs_linear.Time, step_theta_m3.outputs_linear.Data(:,2), '--b', ...
    step_theta_m2.outputs_nonlinear.Time, step_theta_m2.outputs_nonlinear.Data(:,2), '-.r', ...
    step_theta_m3.outputs_nonlinear.Time, step_theta_m3.outputs_nonlinear.Data(:,2), '-.b');
ylim([-15 5]);
xlim([0 50]);
grid on;
subplot(8,4,11)
plot(step_theta_m2.step_linear.Time, step_theta_m2.step_linear.Data(:,3), ':k', ...
    step_theta_m2.outputs_linear.Time, step_theta_m2.outputs_linear.Data(:,3), '--r', ...
    step_theta_m3.outputs_linear.Time, step_theta_m3.outputs_linear.Data(:,3), '--b', ...
    step_theta_m2.outputs_nonlinear.Time, step_theta_m2.outputs_nonlinear.Data(:,3), '-.r', ...
    step_theta_m3.outputs_nonlinear.Time, step_theta_m3.outputs_nonlinear.Data(:,3), '-.b');
ylim([-2 3]);
xlim([0 50]);
grid on;
subplot(8,4,15)
plot(step_theta_m2.outputs_linear.Time, step_theta_m2.outputs_linear.Data(:,4), '--r', ...
    step_theta_m3.outputs_linear.Time, step_theta_m3.outputs_linear.Data(:,4), '--b', ...
    step_theta_m2.outputs_nonlinear.Time, step_theta_m2.outputs_nonlinear.Data(:,4), '-.r', ...
    step_theta_m3.outputs_nonlinear.Time, step_theta_m3.outputs_nonlinear.Data(:,4), '-.b');
ylim([3500 9000]);
xlim([0 50]);
grid on;
subplot(8,4,19)
plot(step_theta_m2.outputs_linear.Time, step_theta_m2.outputs_linear.Data(:,5), '--r', ...
    step_theta_m3.outputs_linear.Time, step_theta_m3.outputs_linear.Data(:,5), '--b', ...
    step_theta_m2.outputs_nonlinear.Time, step_theta_m2.outputs_nonlinear.Data(:,5), '-.r', ...
    step_theta_m3.outputs_nonlinear.Time, step_theta_m3.outputs_nonlinear.Data(:,5), '-.b');
ylim([-60 60]);
xlim([0 50]);
grid on;
subplot(8,4,23)
plot(step_theta_m2.outputs_linear.Time, step_theta_m2.outputs_linear.Data(:,6), '--r', ...
    step_theta_m3.outputs_linear.Time, step_theta_m3.outputs_linear.Data(:,6), '--b', ...
    step_theta_m2.outputs_nonlinear.Time, step_theta_m2.outputs_nonlinear.Data(:,6), '-.r', ...
    step_theta_m3.outputs_nonlinear.Time, step_theta_m3.outputs_nonlinear.Data(:,6), '-.b');
ylim([-10 10]);
xlim([0 50]);
grid on;
subplot(8,4,27)
plot(step_theta_m2.outputs_linear.Time, step_theta_m2.outputs_linear.Data(:,7), '--r', ...
    step_theta_m3.outputs_linear.Time, step_theta_m3.outputs_linear.Data(:,7), '--b', ...
    step_theta_m2.outputs_nonlinear.Time, step_theta_m2.outputs_nonlinear.Data(:,7), '-.r', ...
    step_theta_m3.outputs_nonlinear.Time, step_theta_m3.outputs_nonlinear.Data(:,7), '-.b');
ylim([-3 3]);
xlim([0 50]);
grid on;
subplot(8,4,31)
plot(step_theta_m2.outputs_linear.Time, step_theta_m2.outputs_linear.Data(:,8), '--r', ...
    step_theta_m3.outputs_linear.Time, step_theta_m3.outputs_linear.Data(:,8), '--b', ...
    step_theta_m2.outputs_nonlinear.Time, step_theta_m2.outputs_nonlinear.Data(:,8), '-.r', ...
    step_theta_m3.outputs_nonlinear.Time, step_theta_m3.outputs_nonlinear.Data(:,8), '-.b');
ylim([-600 600]);
xlim([0 50]);
xlabel('Time [s]');
grid on;

subplot(8,4,4)
plot(step_h_m2.outputs_linear.Time, step_h_m2.outputs_linear.Data(:,1), '--r', ...
    step_h_m3.outputs_linear.Time, step_h_m3.outputs_linear.Data(:,1), '--b', ...
    step_h_m2.outputs_nonlinear.Time, step_h_m2.outputs_nonlinear.Data(:,1), '-.r', ...
    step_h_m3.outputs_nonlinear.Time, step_h_m3.outputs_nonlinear.Data(:,1), '-.b');
ylim(1e-3*[-0.5 0.5]);
title('\rm from w_{h1}')
grid on;
subplot(8,4,8)
plot(step_h_m2.outputs_linear.Time, step_h_m2.outputs_linear.Data(:,2), '--r', ...
    step_h_m3.outputs_linear.Time, step_h_m3.outputs_linear.Data(:,2), '--b', ...
    step_h_m2.outputs_nonlinear.Time, step_h_m2.outputs_nonlinear.Data(:,2), '-.r', ...
    step_h_m3.outputs_nonlinear.Time, step_h_m3.outputs_nonlinear.Data(:,2), '-.b');
ylim(1e-3*[-0.5 0.5]);
grid on;
subplot(8,4,12)
plot(step_h_m2.outputs_linear.Time, step_h_m2.outputs_linear.Data(:,3), '--r', ...
    step_h_m3.outputs_linear.Time, step_h_m3.outputs_linear.Data(:,3), '--b', ...
    step_h_m2.outputs_nonlinear.Time, step_h_m2.outputs_nonlinear.Data(:,3), '-.r', ...
    step_h_m3.outputs_nonlinear.Time, step_h_m3.outputs_nonlinear.Data(:,3), '-.b');
ylim([-0.1 0]);
grid on;
subplot(8,4,16)
plot(step_h_m2.step_linear.Time, step_h_m2.step_linear.Data(:,4)+5000, ':k', ...
    step_h_m2.outputs_linear.Time, step_h_m2.outputs_linear.Data(:,4), '--r', ...
    step_h_m3.outputs_linear.Time, step_h_m3.outputs_linear.Data(:,4), '--b', ...
    step_h_m2.outputs_nonlinear.Time, step_h_m2.outputs_nonlinear.Data(:,4), '-.r', ...
    step_h_m3.outputs_nonlinear.Time, step_h_m3.outputs_nonlinear.Data(:,4), '-.b');
ylim([4998 5008]);
grid on;
subplot(8,4,20)
plot(step_h_m2.outputs_linear.Time, step_h_m2.outputs_linear.Data(:,5), '--r', ...
    step_h_m3.outputs_linear.Time, step_h_m3.outputs_linear.Data(:,5), '--b', ...
    step_h_m2.outputs_nonlinear.Time, step_h_m2.outputs_nonlinear.Data(:,5), '-.r', ...
    step_h_m3.outputs_nonlinear.Time, step_h_m3.outputs_nonlinear.Data(:,5), '-.b');
ylim(1e-3*[-0.5 0.5]);
grid on;
subplot(8,4,24)
plot(step_h_m2.outputs_linear.Time, step_h_m2.outputs_linear.Data(:,6), '--r', ...
    step_h_m3.outputs_linear.Time, step_h_m3.outputs_linear.Data(:,6), '--b', ...
    step_h_m2.outputs_nonlinear.Time, step_h_m2.outputs_nonlinear.Data(:,6), '-.r', ...
    step_h_m3.outputs_nonlinear.Time, step_h_m3.outputs_nonlinear.Data(:,6), '-.b');
ylim(1e-3*[-0.5 0.5]);
grid on;
subplot(8,4,28)
plot(step_h_m2.outputs_linear.Time, step_h_m2.outputs_linear.Data(:,7), '--r', ...
    step_h_m3.outputs_linear.Time, step_h_m3.outputs_linear.Data(:,7), '--b', ...
    step_h_m2.outputs_nonlinear.Time, step_h_m2.outputs_nonlinear.Data(:,7), '-.r', ...
    step_h_m3.outputs_nonlinear.Time, step_h_m3.outputs_nonlinear.Data(:,7), '-.b');
ylim(1e-1*[-0.5 0.5]);
grid on;
subplot(8,4,32)
plot(step_h_m2.outputs_linear.Time, step_h_m2.outputs_linear.Data(:,8), '--r', ...
    step_h_m3.outputs_linear.Time, step_h_m3.outputs_linear.Data(:,8), '--b', ...
    step_h_m2.outputs_nonlinear.Time, step_h_m2.outputs_nonlinear.Data(:,8), '-.r', ...
    step_h_m3.outputs_nonlinear.Time, step_h_m3.outputs_nonlinear.Data(:,8), '-.b');
ylim([-15 -5]);
xlabel('Time [s]');
grid on;
set(gcf, 'Position',[383 42 850 960]);

%% plot differenz flugzeugpositionen
f_pos = figure;
subplot(1,4,1)
plot(step_v_m2.difference_position_nonlinear.Time, step_v_m2.difference_position_nonlinear.Data(:,1), '-.r', ...
    step_v_m2.difference_position_nonlinear.Time, step_v_m2.difference_position_nonlinear.Data(:,2), '-.b', ...
    step_v_m2.difference_position_nonlinear.Time, step_v_m2.difference_position_nonlinear.Data(:,3), '-.g', ...
    step_v_m3.difference_position_nonlinear.Time, step_v_m3.difference_position_nonlinear.Data(:,1), '--r', ...
    step_v_m3.difference_position_nonlinear.Time, step_v_m3.difference_position_nonlinear.Data(:,2), '--b', ...
    step_v_m3.difference_position_nonlinear.Time, step_v_m3.difference_position_nonlinear.Data(:,3), '--g');
legend('\Delta x Modell 2', '\Delta y Modell 2', '\Delta h Modell 2', ...
    '\Delta x Modell 3', '\Delta y Modell 3', '\Delta h Modell 3', 'Location', 'southeast')
ylim([-15 5]);
title('\rm from w_{v1}')
ylabel('Distance [m]');
xlabel('Time [s]');
pbaspect([1.5 2 1])
grid on;
subplot(1,4,2)
plot(step_phi_m2.difference_position_nonlinear.Time, step_phi_m2.difference_position_nonlinear.Data(:,1), '-.r', ...
    step_phi_m2.difference_position_nonlinear.Time, step_phi_m2.difference_position_nonlinear.Data(:,2), '-.b', ...
    step_phi_m2.difference_position_nonlinear.Time, step_phi_m2.difference_position_nonlinear.Data(:,3), '-.g', ...
    step_phi_m3.difference_position_nonlinear.Time, step_phi_m3.difference_position_nonlinear.Data(:,1), '--r', ...
    step_phi_m3.difference_position_nonlinear.Time, step_phi_m3.difference_position_nonlinear.Data(:,2), '--b', ...
    step_phi_m3.difference_position_nonlinear.Time, step_phi_m3.difference_position_nonlinear.Data(:,3), '--g');
% ylim([-15 5]);
title('\rm from w_{\Phi1}')
xlabel('Time [s]');
pbaspect([1.5 2 1])
grid on;
subplot(1,4,3)
plot(step_theta_m2.difference_position_nonlinear.Time, step_theta_m2.difference_position_nonlinear.Data(:,1), '-.r', ...
    step_theta_m2.difference_position_nonlinear.Time, step_theta_m2.difference_position_nonlinear.Data(:,2), '-.b', ...
    step_theta_m2.difference_position_nonlinear.Time, step_theta_m2.difference_position_nonlinear.Data(:,3), '-.g', ...
    step_theta_m3.difference_position_nonlinear.Time, step_theta_m3.difference_position_nonlinear.Data(:,1), '--r', ...
    step_theta_m3.difference_position_nonlinear.Time, step_theta_m3.difference_position_nonlinear.Data(:,2), '--b', ...
    step_theta_m3.difference_position_nonlinear.Time, step_theta_m3.difference_position_nonlinear.Data(:,3), '--g');
% ylim([-15 5]);
title('\rm from w_{\Theta1}')
xlabel('Time [s]');
pbaspect([1.5 2 1])
grid on;
subplot(1,4,4)
plot(step_h_m2.difference_position_nonlinear.Time, step_h_m2.difference_position_nonlinear.Data(:,1), '-.r', ...
    step_h_m2.difference_position_nonlinear.Time, step_h_m2.difference_position_nonlinear.Data(:,2), '-.b', ...
    step_h_m2.difference_position_nonlinear.Time, step_h_m2.difference_position_nonlinear.Data(:,3), '-.g', ...
    step_h_m3.difference_position_nonlinear.Time, step_h_m3.difference_position_nonlinear.Data(:,1), '--r', ...
    step_h_m3.difference_position_nonlinear.Time, step_h_m3.difference_position_nonlinear.Data(:,2), '--b', ...
    step_h_m3.difference_position_nonlinear.Time, step_h_m3.difference_position_nonlinear.Data(:,3), '--g');
% ylim([-15 5]);
title('\rm from w_{h1}')
xlabel('Time [s]');
pbaspect([1.5 2 1])
grid on;
